variables:
  VERSION: 1.0.${CI_PIPELINE_ID}

include:
  - project: 'templates/ci'
    file: 'DockerInDockerTemplate.yml'

stages:
  - build
  - test

build-frontend:
  stage: build
  image: docker:20.10.12-dind-rootless
  before_script:
    - until docker info; do sleep 1; done
    # переменные CI_REGISTRY_USER, CI_REGISTRY_PASSWORD, CI_REGISTRY генерятся Гитлабом, их задавать не надо!
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - cd frontend
    - >
      docker build
      --build-arg VERSION=$VERSION
      --tag $CI_REGISTRY_IMAGE/sausage-frontend:${VERSION}
      .
#    - docker push $CI_REGISTRY_IMAGE/sausage-frontend:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE/sausage-frontend:${VERSION}

#  rules:
#      - changes:
#           - frontend/*


sonarq-frontend-check:
  stage: test
  dependencies:
    - build-frontend
  image:
    name: sonarsource/sonar-scanner-cli:4.6
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  script:
    - cd frontend
    - sonar-scanner
      -Dsonar.projectKey=02_alexander_volokhov_frontend
      -Dsonar.projectName=02_alexander_volokhov_frontend
      -Dsonar.host.url=$SONAR_URL
      -Dsonar.login=$SONAR_TOKEN
#      -Dsonar.qualitygate.wait=true


   


