variables:
  VERSION: 1.0.${CI_PIPELINE_ID}

stages:
  - build
  - release

build:
stage: build
script:
  - cd frontend
  - npm install
  - npm run build
  - cd ..
  - mkdir sausage-store-${VERSION}
  - mv frontend/dist/frontend sausage-store-${VERSION}/public_html
artifacts:
paths:
  - sausage-store-${VERSION}/public_html
rules:
  - changes:
  - frontend/*
sast:
  stage: test
include:
  - template: Security/SAST.gitlab-ci.yml
sonarq-frontend-check:
  stage: test
  image:
    name: sonarsource/sonar-scanner-cli:4.6
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  script:
    - cd frontend
    - sonar-scanner
      -Dsonar.qualitygate.wait=true
      -Dsonar.projectKey=02_alexander_volokhov_frontend
      -Dsonar.projectName=02_alexander_volokhov_frontend
      -Dsonar.host.url=$SONAR_URL
      -Dsonar.login=$SONAR_TOKEN

release:
stage: release
script:
  - tar czvf sausage-store-${VERSION}.tar.gz sausage-store-${VERSION}/public_html #!
  - curl -v -u "${NEXUS_REPO_USER}:${NEXUS_REPO_PASS}" --upload-file sausage-store-${VERSION}.tar.gz ${NEXUS_FRONTEND_REPO_URL}/sausage-store/${VERSION}/sausage-store-${VERSION}.tar.gz