variables:
  VERSION: 1.0.${CI_PIPELINE_ID}
  MAVEN_REPO_PATH: ./.m2/repository
   
stages:
    - build
    - test
    - release
 
build-job:
  stage: build
script:
  - cd backend
  - mvn package -Dversion.application=${VERSION} -Dmaven.repo.local=${MAVEN_REPO_PATH}
rules:
  changes:
  - backend/*
artifacts:
  paths:
  - sausage-store-${VERSION}/sausage-store-${VERSION}.jar
spotbugs-sast:
  variables:
    COMPILE: "false"
    MAVEN_REPO_PATH: ${MAVEN_REPO_PATH}
sast:
  stage: test
include:
  - template: Security/SAST.gitlab-ci.yml
sonarq-backend-check:
  stage: test
    image: maven:3.8.3-openjdk-16
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  script:
    - cd backend
    - mvn verify sonar:sonar
      -Dsonar.qualitygate.wait=true
      -Dsonar.projectKey=02_alexander_volokhov_backend
      -Dsonar.projectName=02_alexander_volokhov_backend
      -Dsonar.host.url=$SONAR_URL
      -Dsonar.login=$SONAR_TOKEN

release:
   stage: release
   script:
    - cd backend
    - mvn deploy -DskipTests -Dversion.application=${VERSION} -Dmaven.repo.local=${MAVEN_REPO_PATH} -s settings.xml
rules:
  changes:
  - backend/* 
