include:
  - project: 'templates/ci'
    file: 'DockerInDockerTemplate.yml'
  - template: Security/SAST.gitlab-ci.yml

variables:
  VERSION: 1.0.${CI_PIPELINE_ID}
  MAVEN_REPO_PATH: ${CI_PROJECT_DIR}/.m2/repository
  # JAVA_OPTS: -XX:MaxRAMPercentage=90
cache:
  paths:
    - ${CI_PROJECT_DIR}/.m2/repository

stages:
- build
- test
- docker
- deploy

build-backend-report:
  stage: build
  script:
    - echo "ARTIFACT_JOB_ID=${CI_JOB_ID}" > CI_JOB_ID.TXT
    - cd backend-report
    - mvn package -DskipTests -Dversion.application=${VERSION}
    - mkdir backend-report-${VERSION}
    - pwd
    - ls target
    - mv target/sausage-store-report-${VERSION}.jar backend-report-${VERSION}/sausage-store-report-${VERSION}.jar
    - pwd
    - ls backend-report-${VERSION}
  artifacts:
    paths:
    - ${CI_PROJECT_DIR}/backend-report/backend-report-${VERSION}/sausage-store-report-${VERSION}.jar
    - ${MAVEN_REPO_PATH}
    reports:
      dotenv: CI_JOB_ID.TXT
  
spotbugs-sast:       
  variables:
    COMPILE: "false"
    MAVEN_REPO_PATH: ${CI_PROJECT_DIR}/.m2/repository
sast:
  stage: test

sonarq-backend-check:
  stage: test
  dependencies:
    - build-backend-report
  image: maven:3.8.3-openjdk-16
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  script:
    - cd backend
    - mvn verify sonar:sonar
      -Dsonar.qualitygate.wait=true
      -Dsonar.projectKey=02_alexander_volokhov_backend
      -Dsonar.projectName=02_alexander_volokhov_backend
      -Dsonar.host.url=$SONAR_URL
      -Dsonar.login=$SONAR_TOKEN 

build-docker:
  stage: docker
  dependencies:
    - build-backend-report
  image: docker:20.10.12-dind-rootless
  before_script:
    - until docker info; do sleep 1; done
    # переменные CI_REGISTRY_USER, CI_REGISTRY_PASSWORD, CI_REGISTRY генерятся Гитлабом, их задавать не надо!
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - cd backend-report
    - >
      docker build
      --build-arg VERSION=$VERSION
      --tag $CI_REGISTRY_IMAGE/backend-report:${VERSION}
      .
    #- docker push $CI_REGISTRY_IMAGE/sausage-backend:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE/backend-report:${VERSION}
